# DataFrames I

In [1]:
import pandas as pd

## Methods and Attributes between Series and DataFrames
- A `DataFrame` is a 2-dimensional table consisting of rows and columns.
- Like with a `Series`, Pandas assigns an index position/label to each `DataFrame` row.
- Pandas uses a `NaN` designation for cells that have a missing value.
- The `pd.read_csv` function imports a `DataFrame` by default.
- The `nba.csv` dataset is a collection of basketball players.
- The last row in the dataset is completely empty.

In [49]:
nba = pd.read_csv("nba.csv")
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,F,6-10,220.0,Georgia,4000000.0
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000.0
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000.0
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000.0
4,Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,NaN
...,...,...,...,...,...,...,...
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000.0
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000.0
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,NaN,3000000.0
525,Will Riley,Washington Wizards,G-F,6-8,186.0,Illinois,4300000.0


- The `DataFrame` and `Series` have common and exclusive methods/attributes.
- Some methods/attributes will return different types of data.

- The `head` method returns rows from the start of the `DataFrame`.
- The `tail` method returns rows from the end of the `DataFrame`.

In [3]:
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,F,6-10,220.0,Georgia,4000000.0
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000.0
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000.0
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000.0
4,Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,NaN


In [4]:
nba.tail()

,Name,Team,Position,Height,Weight,College,Salary
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000.0
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000.0
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,NaN,3000000.0
525,Will Riley,Washington Wizards,G-F,6-8,186.0,Illinois,4300000.0
526,NaN,NaN,NaN,NaN,NaN,NaN,NaN


- The `index` attribute stores the object that holds the index labels.

In [5]:
nba.index

RangeIndex(start=0, stop=527, step=1)

- The `shape` attribute is a tuple with the dimensions (height x width) of the data structure.

In [6]:
nba.shape

(527, 7)

- The `dtypes` attribute holds the data types.
- The `DataFrame` has multiple columns, so Pandas creates a `Series` where the index labels are the column names and the values are their data types.

In [7]:
nba.dtypes

Name            str
Team            str
Position        str
Height          str
Weight      float64
College         str
Salary      float64
dtype: object

- The `hasnans` attribute returns `True` if a `Series` contains any missing values.
- The attribute does not exist on a `DataFrame`.

In [17]:
# nba.hasnans This gives an error
weights = pd.Series(nba["Weight"])
weights.hasnans

True

- The `columns` attribute returns the column labels of a `DataFrame`.
- The attribute does not exist on a `Series`.

In [11]:
nba.columns

Index(['Name', 'Team', 'Position', 'Height', 'Weight', 'College', 'Salary'], dtype='str')

- The `axes` attribute returns a list of the axis indexes.
- The `Series` has only one index, so the list has 1 entry.
- The `DataFrame` has two indexes (rows and columns), so the list has 2 entries.

In [12]:
nba.axes

[RangeIndex(start=0, stop=527, step=1),
 Index(['Name', 'Team', 'Position', 'Height', 'Weight', 'College', 'Salary'], dtype='str')]

- The `info` method returns a summary of the pandas object.
- The output includes the index type, a count of non-null values, the data types, and the memory usage.

In [13]:
nba.info()

<class 'pandas.DataFrame'>
RangeIndex: 527 entries, 0 to 526
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      526 non-null    str    
 1   Team      526 non-null    str    
 2   Position  526 non-null    str    
 3   Height    526 non-null    str    
 4   Weight    526 non-null    float64
 5   College   485 non-null    str    
 6   Salary    474 non-null    float64
dtypes: float64(2), str(5)
memory usage: 50.8 KB


- The `info` method on a `DataFrame` outputs the details _per_ column.

## Differences between Shared Methods
- The same method may work differently on a `Series` vs. a `DataFrame`.

- The `sum` method adds a `Series`'s values. There is only one direction to add.

In [21]:
s = pd.Series([1, 2, 3, 4, 5])
revenue = pd.read_csv("revenue.csv", index_col="Date")
revenue.head()

,New York,Los Angeles,Miami
Date,,,
1/1/26,985,122,499
1/2/26,738,788,534
1/3/26,14,20,933
1/4/26,730,904,885
1/5/26,114,71,253


In [24]:
s.sum()

np.int64(15)

- On a `DataFrame`, the `sum` method defaults to adding the column values.
- The method returns a `Series` where the index labels are the column names and the values are the sum totals.
- The `axis` parameter customizes the direction that we add across. Pass `"index"` or `0` to add values by traversing the rows.

In [23]:
revenue.sum()

New York       5475
Los Angeles    5134
Miami          5641
dtype: int64

- Pass the `axis` parameter an argument of `"columns"` to calculate the sum of each row's values.
- We are traversing the "columns" in calculating the sum rather than traversing the "index".

In [25]:
revenue.sum(axis="columns")

Date
1/1/26     1606
1/2/26     2060
1/3/26      967
1/4/26     2519
1/5/26      438
1/6/26     1935
1/7/26     1234
1/8/26     2313
1/9/26     2623
1/10/26     555
dtype: int64

- Now that we have a `Series` of numbers, we can also calculate total business revenue by invoking `sum`.

In [ ]:
# This is a sum of sums
revenue.sum(axis=0).sum()

np.int64(16250)

## Select One Column from a DataFrame

- Pandas will define a `DataFrame` attribute for each column name.
- Use attribute syntax (`df.column_name`) to select a column.
- Pandas extracts the `DataFrame` column as a `Series`.

In [29]:
nba.College

0       Georgia
1      Oklahoma
2        Lehigh
3      Michigan
4       Arizona
         ...   
522    Oklahoma
523       Texas
524         NaN
525    Illinois
526         NaN
Name: College, Length: 527, dtype: str

In [31]:
type(nba.College)

pandas.Series

- Case-sensitivity matters. Write out the column name with correct capitalization.
- The attribute accesssyntax will not work if the column name has spaces.

- The extracted column is a valid `Series` with all of its regular methods.
- The `value_counts` counts the number of times that each distinct value occurs.

In [32]:
nba.College.value_counts()

College
Duke                      27
Kentucky                  27
Arizona                   14
Michigan                  13
Gonzaga                   12
                          ..
Bowling Green              1
Milwaukee                  1
Seton Hall                 1
Purdue Fort Wayne          1
Bosnia and Herzegovina     1
Name: count, Length: 137, dtype: int64

- Square bracket syntax also extracts a column (`df["column name"]`).
- The syntax will not work if the column name has spaces or special symbols.

In [33]:
nba["College"]

0       Georgia
1      Oklahoma
2        Lehigh
3      Michigan
4       Arizona
         ...   
522    Oklahoma
523       Texas
524         NaN
525    Illinois
526         NaN
Name: College, Length: 527, dtype: str

- Recall Pandas 3's **Copy-on-Write** principles.
- Extracting a column returns an object that behaves as a copy.
- The underlying data is still shared between `Series` and `DataFrame`.
- When we perform a mutative operation on the `Series`, Pandas will create a copy of the underlying data.
- In summary, mutating the extracted `Series` will **not** mutate the original `DataFrame`.

In [34]:
colleges = nba.College
colleges

0       Georgia
1      Oklahoma
2        Lehigh
3      Michigan
4       Arizona
         ...   
522    Oklahoma
523       Texas
524         NaN
525    Illinois
526         NaN
Name: College, Length: 527, dtype: str

In [35]:
colleges.iloc[0] = "Uvic"
colleges.head()

0        Uvic
1    Oklahoma
2      Lehigh
3    Michigan
4     Arizona
Name: College, dtype: str

In [41]:
"Uvic" in nba.Team.values
# It was not changed in the original. Just a copy

False

## Select Multiple Columns from a DataFrame
- Use square brackets with a list of column names to extract multiple `DataFrame` columns.
- Pandas stores the result in a new `DataFrame` that behaves like a copy.

In [43]:
names_and_heights = nba[["Name", "Height"]]
names_and_heights

,Name,Height
0,Asa Newell,6-10
1,Buddy Hield,6-4
2,C.J. McCollum,6-3
3,Caleb Houstan,6-8
4,Christian Koloko,7-0
...,...,...
522,Trae Young,6-1
523,Tre Johnson,6-5
524,Tristan Vukcevic,6-11
525,Will Riley,6-8


- The order of list elements impacts the order of the `DataFrame`'s columns.

In [44]:
heights_and_names = nba[["Height", "Name"]]
heights_and_names

,Height,Name
0,6-10,Asa Newell
1,6-4,Buddy Hield
2,6-3,C.J. McCollum
3,6-8,Caleb Houstan
4,7-0,Christian Koloko
...,...,...
522,6-1,Trae Young
523,6-5,Tre Johnson
524,6-11,Tristan Vukcevic
525,6-8,Will Riley


- Assign the list to a variable for an easier syntax.

## Add New Column to DataFrame
- Use square bracket extraction syntax with an equal sign to add a new `Series` to a `DataFrame`.
- Be careful here. If you reference an existing column, Pandas will overwrite it.

In [45]:
nba["Sportsmanship"] = "Poor"
nba.head()

,Name,Team,Position,Height,Weight,College,Salary,Sportsmanship
0,Asa Newell,Atlanta Hawks,F,6-10,220.0,Georgia,4000000.0,Poor
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000.0,Poor
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000.0,Poor
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000.0,Poor
4,Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,NaN,Poor


In [50]:
nba.insert(loc=2, column="Sneeze Velocity m/s", value=36)
nba.head()

,Name,Team,Sneeze Velocity m/s,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,36,F,6-10,220.0,Georgia,4000000.0
1,Buddy Hield,Atlanta Hawks,36,G-F,6-4,220.0,Oklahoma,9700000.0
2,C.J. McCollum,Atlanta Hawks,36,G,6-3,190.0,Lehigh,30700000.0
3,Caleb Houstan,Atlanta Hawks,36,F,6-8,205.0,Michigan,1300000.0
4,Christian Koloko,Atlanta Hawks,36,C,7-0,230.0,Arizona,NaN


- The `insert` method adds an column at a specific column index.
- The `insert` method mutates the existing `DataFrame`. It does not return a value.
- The column index starts counting from 0. The `Name` column is index 0.
- `loc=3` means the new columns becomes the 4th column (after `Position`).

- The right-hand side of the equal sign can also be a `Series`.
- Let's imagine a scenario where each player's salary doubled.

In [51]:
nba["Salary"] = nba["Salary"].mul(2)
nba.head()

,Name,Team,Sneeze Velocity m/s,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,36,F,6-10,220.0,Georgia,8000000.0
1,Buddy Hield,Atlanta Hawks,36,G-F,6-4,220.0,Oklahoma,19400000.0
2,C.J. McCollum,Atlanta Hawks,36,G,6-3,190.0,Lehigh,61400000.0
3,Caleb Houstan,Atlanta Hawks,36,F,6-8,205.0,Michigan,2600000.0
4,Christian Koloko,Atlanta Hawks,36,C,7-0,230.0,Arizona,NaN


- Here's another example with subtraction.

In [52]:
nba["Salary"] = nba["Salary"].sub(20000)
nba.head()

,Name,Team,Sneeze Velocity m/s,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,36,F,6-10,220.0,Georgia,7980000.0
1,Buddy Hield,Atlanta Hawks,36,G-F,6-4,220.0,Oklahoma,19380000.0
2,C.J. McCollum,Atlanta Hawks,36,G,6-3,190.0,Lehigh,61380000.0
3,Caleb Houstan,Atlanta Hawks,36,F,6-8,205.0,Michigan,2580000.0
4,Christian Koloko,Atlanta Hawks,36,C,7-0,230.0,Arizona,NaN


## Create Columns with the assign Method
- The `assign` method returns a new `DataFrame`  with one or more new columns.
- The method differs from direct assignment (`df["col"] = value`), which **mutates** the original `DataFrame`.

- Pass keyword arguments where the parameter is the new column name and the value is a `Series`.

In [54]:
nba.assign(Salary_Doubled=nba["Salary"] * 2, Weight_Minus_10=nba["Weight"] - 10)

,Name,Team,Sneeze Velocity m/s,Position,Height,Weight,College,Salary,Salary_Doubled,Weight_Minus_10
0,Asa Newell,Atlanta Hawks,36,F,6-10,220.0,Georgia,7980000.0,15960000.0,210.0
1,Buddy Hield,Atlanta Hawks,36,G-F,6-4,220.0,Oklahoma,19380000.0,38760000.0,210.0
2,C.J. McCollum,Atlanta Hawks,36,G,6-3,190.0,Lehigh,61380000.0,122760000.0,180.0
3,Caleb Houstan,Atlanta Hawks,36,F,6-8,205.0,Michigan,2580000.0,5160000.0,195.0
4,Christian Koloko,Atlanta Hawks,36,C,7-0,230.0,Arizona,NaN,NaN,220.0
...,...,...,...,...,...,...,...,...,...,...
522,Trae Young,Washington Wizards,36,G,6-1,164.0,Oklahoma,94980000.0,189960000.0,154.0
523,Tre Johnson,Washington Wizards,36,G,6-5,190.0,Texas,18780000.0,37560000.0,180.0
524,Tristan Vukcevic,Washington Wizards,36,C,6-11,220.0,NaN,5980000.0,11960000.0,210.0
525,Will Riley,Washington Wizards,36,G-F,6-8,186.0,Illinois,8580000.0,17160000.0,176.0


## Drop Rows with Missing Values
- Pandas designates missing values with a `NaN`.

- The `dropna` method deletes rows with missing values.
- The method's default behavior is to remove a row if it contains *any* missing values.

In [55]:
nba.tail()

,Name,Team,Sneeze Velocity m/s,Position,Height,Weight,College,Salary
522,Trae Young,Washington Wizards,36,G,6-1,164.0,Oklahoma,94980000.0
523,Tre Johnson,Washington Wizards,36,G,6-5,190.0,Texas,18780000.0
524,Tristan Vukcevic,Washington Wizards,36,C,6-11,220.0,NaN,5980000.0
525,Will Riley,Washington Wizards,36,G-F,6-8,186.0,Illinois,8580000.0
526,NaN,NaN,36,NaN,NaN,NaN,NaN,NaN


- Pass the `how` parameter an argument of "all" to remove rows where all the values are `NaN`.
- This solution effectively removes the final `DataFrame` rows which holds only missing values.

In [63]:
nba.dropna(how="any").tail()

,Name,Team,Sneeze Velocity m/s,Position,Height,Weight,College,Salary
519,Kyshawn George,Washington Wizards,36,G-F,6-8,205.0,Miami (FL),7580000.0
520,Leaky Black,Washington Wizards,36,F,6-9,218.0,North Carolina,1180000.0
522,Trae Young,Washington Wizards,36,G,6-1,164.0,Oklahoma,94980000.0
523,Tre Johnson,Washington Wizards,36,G,6-5,190.0,Texas,18780000.0
525,Will Riley,Washington Wizards,36,G-F,6-8,186.0,Illinois,8580000.0


- The `subset` parameter limits the columns that pandas will use to drop rows with missing values.
- The next example drop rows with a missing value in either the `College` or `Salary` column (or both).

In [64]:
nba.dropna(subset=["College", "Salary"]).tail()

,Name,Team,Sneeze Velocity m/s,Position,Height,Weight,College,Salary
519,Kyshawn George,Washington Wizards,36,G-F,6-8,205.0,Miami (FL),7580000.0
520,Leaky Black,Washington Wizards,36,F,6-9,218.0,North Carolina,1180000.0
522,Trae Young,Washington Wizards,36,G,6-1,164.0,Oklahoma,94980000.0
523,Tre Johnson,Washington Wizards,36,G,6-5,190.0,Texas,18780000.0
525,Will Riley,Washington Wizards,36,G-F,6-8,186.0,Illinois,8580000.0


- The `thresh` parameter keeps rows with a minimum number of present values.
- `thresh` is useful when some missing data is acceptable and you want to drop rows that are *mostly* empty.
- The next example passes an argument of 5, which keeps rows with at least 5 non-null values (out of 7 columns).

In [65]:
nba.dropna(thresh=5)

,Name,Team,Sneeze Velocity m/s,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,36,F,6-10,220.0,Georgia,7980000.0
1,Buddy Hield,Atlanta Hawks,36,G-F,6-4,220.0,Oklahoma,19380000.0
2,C.J. McCollum,Atlanta Hawks,36,G,6-3,190.0,Lehigh,61380000.0
3,Caleb Houstan,Atlanta Hawks,36,F,6-8,205.0,Michigan,2580000.0
4,Christian Koloko,Atlanta Hawks,36,C,7-0,230.0,Arizona,NaN
...,...,...,...,...,...,...,...,...
521,Sharife Cooper,Washington Wizards,36,G,6-1,180.0,Auburn,NaN
522,Trae Young,Washington Wizards,36,G,6-1,164.0,Oklahoma,94980000.0
523,Tre Johnson,Washington Wizards,36,G,6-5,190.0,Texas,18780000.0
524,Tristan Vukcevic,Washington Wizards,36,C,6-11,220.0,NaN,5980000.0


## Fill in Missing Values with the fillna Method
- The `fillna` method replaces missing `NaN` values with its argument.
- The `fillna` method is available on both `DataFrame` and `Series` objects.
- The `fillna` method returns a new object with missing values replaced.  The original is not mutated.

In [66]:
nba.fillna(0).tail()

,Name,Team,Sneeze Velocity m/s,Position,Height,Weight,College,Salary
522,Trae Young,Washington Wizards,36,G,6-1,164.0,Oklahoma,94980000.0
523,Tre Johnson,Washington Wizards,36,G,6-5,190.0,Texas,18780000.0
524,Tristan Vukcevic,Washington Wizards,36,C,6-11,220.0,0,5980000.0
525,Will Riley,Washington Wizards,36,G-F,6-8,186.0,Illinois,8580000.0
526,0,0,36,0,0,0.0,0,0.0


- Pass `fillna` a **dictionary** to specify replacement values _per_ column.
- The dictionary keys will be the column names, and the dictionary values are the replacement values.

In [68]:
nba.fillna({
  "College": "Uvic"
}).tail()

,Name,Team,Sneeze Velocity m/s,Position,Height,Weight,College,Salary
522,Trae Young,Washington Wizards,36,G,6-1,164.0,Oklahoma,94980000.0
523,Tre Johnson,Washington Wizards,36,G,6-5,190.0,Texas,18780000.0
524,Tristan Vukcevic,Washington Wizards,36,C,6-11,220.0,Uvic,5980000.0
525,Will Riley,Washington Wizards,36,G-F,6-8,186.0,Illinois,8580000.0
526,NaN,NaN,36,NaN,NaN,NaN,Uvic,NaN


- The next example replaces `NaN` values with 0 in the `Salary` column.

In [70]:
nba.fillna({
  "Salary": 0
}).head()

,Name,Team,Sneeze Velocity m/s,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,36,F,6-10,220.0,Georgia,7980000.0
1,Buddy Hield,Atlanta Hawks,36,G-F,6-4,220.0,Oklahoma,19380000.0
2,C.J. McCollum,Atlanta Hawks,36,G,6-3,190.0,Lehigh,61380000.0
3,Caleb Houstan,Atlanta Hawks,36,F,6-8,205.0,Michigan,2580000.0
4,Christian Koloko,Atlanta Hawks,36,C,7-0,230.0,Arizona,0.0


## Fill Missing Values with a Forward Fill or Back Fill
- Forward fills and backward fills are two alternate stategies for replacing missing values.
- Fills are ideal when the previous or next observation is a reasonable estimate for a missing value.
- The `temperatures.csv` file has missing values in the `High Temp` column.
- Example: When measuring temperatures, it's reasonable to guess that a day's temperature will be similar to the one on the previous or next day.

In [71]:
temperatures = pd.read_csv("temperatures.csv")
temperatures.head()

,Date,High Temp
0,2026-01-01,34.0
1,2026-01-02,36.0
2,2026-01-03,33.0
3,2026-01-04,NaN
4,2026-01-05,38.0


- The `ffill` method **forward-fills** missing values.
- Pandas replaces each `NaN` with the last valid value above it.
- For example, index 2's value of 33.0 replaces index 3's missing `NaN` value.

In [73]:
temperatures.ffill().head()

,Date,High Temp
0,2026-01-01,34.0
1,2026-01-02,36.0
2,2026-01-03,33.0
3,2026-01-04,33.0
4,2026-01-05,38.0


- The `bfill` method **backward-fills** missing values.
- Pandas replaces each `NaN` with the next valid value below it.
- For example, index 4's value of 38.0 replaces index 3's missing `NaN` value.

In [74]:
temperatures.bfill().head()

,Date,High Temp
0,2026-01-01,34.0
1,2026-01-02,36.0
2,2026-01-03,33.0
3,2026-01-04,38.0
4,2026-01-05,38.0


- The `limit` parameter places a boundary on how many consecutive `NaN` values to fill.
- The values at row indexes 9, 10, and 11 are all `NaN`.
- An argument of 1 replaces 1 `NaN` value in the sequence (index 9) while keeping the other `NaN`s (index 10, 11).

In [75]:
temperatures.ffill(limit=2).head(15)

,Date,High Temp
0,2026-01-01,34.0
1,2026-01-02,36.0
2,2026-01-03,33.0
3,2026-01-04,33.0
4,2026-01-05,38.0
5,2026-01-06,41.0
6,2026-01-07,43.0
7,2026-01-08,45.0
8,2026-01-09,44.0
9,2026-01-10,44.0


## Convert Data Types with the astype Method I
- The `astype` method converts a `Series's` values to a specified type.
- Developers sometimes use the word "cast" to describe type conversion (i.e., "we cast this number from int to float').
- Pandas cannot convert `NaN` values to numeric types, so we need to eliminate/replace them before we perform the conversion.

In [76]:
nba = pd.read_csv("nba.csv").dropna(how="all").fillna({"Salary": 0})
nba.tail()

,Name,Team,Position,Height,Weight,College,Salary
521,Sharife Cooper,Washington Wizards,G,6-1,180.0,Auburn,0.0
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000.0
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000.0
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,NaN,3000000.0
525,Will Riley,Washington Wizards,G-F,6-8,186.0,Illinois,4300000.0


- Pass in the specified type as either a string or the core Python data type.
- The `dtypes` attribute returns a `Series` with the `DataFrame`'s columns and their types.

In [77]:
nba.dtypes

Name            str
Team            str
Position        str
Height          str
Weight      float64
College         str
Salary      float64
dtype: object

In [78]:
nba["Salary"].astype(int)

0       4000000
1       9700000
2      30700000
3       1300000
4             0
         ...   
521           0
522    47500000
523     9400000
524     3000000
525     4300000
Name: Salary, Length: 526, dtype: int64

- We can then use the assignment operator (`=`) to replace the column.

In [79]:
nba["Salary"] = nba["Salary"].astype(int)
nba.dtypes

Name            str
Team            str
Position        str
Height          str
Weight      float64
College         str
Salary        int64
dtype: object

- The second option is to invoke `astype` on the `DataFrame` and pass in a dictionary.
- The keys should be the column names, and the values should be the desired data types.

In [80]:
nba.astype({"Salary": int})

,Name,Team,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,F,6-10,220.0,Georgia,4000000
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000
4,Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,0
...,...,...,...,...,...,...,...
521,Sharife Cooper,Washington Wizards,G,6-1,180.0,Auburn,0
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,NaN,3000000


- A 64-bit integer (`int64`) can represent values from -9,223,372,036,854,775,808 (quadrillion) to 9,223,372,036,854,775,807.
- A 32-bit integer (`int32`) can represent values from -2,147,483,648 to 2,147,483,647.
- A 16-bit integer (`int16`) can represent values from -32,768 to 32,767.
- A 32-bit integer should be large enough to model every salary in the dataset.
- The `memory_usage` method returns the amount of bytes that each columnn's data occupies in memory.

In [ ]:
nba.memory_usage()

Index         132
Name        11229
Team        12734
Position     5032
Height       5930
Weight       4208
College      8512
Salary       4208
dtype: int64

- Pass the `astype` method an instance of a data type at the top-level of pandas.

In [84]:
nba["Salary"] = nba["Salary"].astype(pd.Int32Dtype())
nba.dtypes

Name            str
Team            str
Position        str
Height          str
Weight      float64
College         str
Salary        Int32
dtype: object

- The data type will update from `int64` to `Int32`.
- Notice the difference in casing. The two are actually different types from different libraries.
- `int64` comes from `numpy` and `Int32` comes from Pandas.
- The Pandas integers support missing values, while the NumPy integers do not support them.

## Convert to Numbers with the to_numeric Function
- The `pd.to_numeric` function converts values to a numeric type (`int` or `float`).

In [86]:
messy = pd.Series(["10", "20", "thirty", "", "40", "50.5"])
messy

0        10
1        20
2    thirty
3          
4        40
5      50.5
dtype: str

- The `astype` method will fail if Pandas cannot convert a value to the specified type.

- The `pd.to_numeric` function attempts to convert to a numeric data type (integer or float)
- The `errors` parameter sets what happens when Pandas cannot convert a value.
- An argument of `raise` (the default) raises an exception on failure.
- An argument of `coerce` converts failures to `NaN`.

In [88]:
pd.to_numeric(messy, errors="coerce")

0    10.0
1    20.0
2     NaN
3     NaN
4    40.0
5    50.5
dtype: float64

## Select Columns by Type with the select_dtypes Method
- The `select_dtypes` method targets columns by their data types.
- The `include` and `exclude` parameters both accept data types as strings.
- The `include` parameter keeps the columns matching the specified type(s) (e.g., `"number"`, `"str"`, `"category"`).
- The `exclude` parameter drops columns matching the specified type.

In [89]:
nba.tail()

,Name,Team,Position,Height,Weight,College,Salary
521,Sharife Cooper,Washington Wizards,G,6-1,180.0,Auburn,0
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,NaN,3000000
525,Will Riley,Washington Wizards,G-F,6-8,186.0,Illinois,4300000


In [90]:
nba.dtypes

Name            str
Team            str
Position        str
Height          str
Weight      float64
College         str
Salary        Int32
dtype: object

- The next example targets all numeric columns (integers and floats).

In [91]:
nba.select_dtypes(include="number")

,Weight,Salary
0,220.0,4000000
1,220.0,9700000
2,190.0,30700000
3,205.0,1300000
4,230.0,0
...,...,...
521,180.0,0
522,164.0,47500000
523,190.0,9400000
524,220.0,3000000


- The next example targets string columns

In [92]:
nba.select_dtypes(include="string")

,Name,Team,Position,Height,College
0,Asa Newell,Atlanta Hawks,F,6-10,Georgia
1,Buddy Hield,Atlanta Hawks,G-F,6-4,Oklahoma
2,C.J. McCollum,Atlanta Hawks,G,6-3,Lehigh
3,Caleb Houstan,Atlanta Hawks,F,6-8,Michigan
4,Christian Koloko,Atlanta Hawks,C,7-0,Arizona
...,...,...,...,...,...
521,Sharife Cooper,Washington Wizards,G,6-1,Auburn
522,Trae Young,Washington Wizards,G,6-1,Oklahoma
523,Tre Johnson,Washington Wizards,G,6-5,Texas
524,Tristan Vukcevic,Washington Wizards,C,6-11,NaN


We can also exclude types to get a similar result

In [93]:
nba.select_dtypes(exclude="number")

,Name,Team,Position,Height,College
0,Asa Newell,Atlanta Hawks,F,6-10,Georgia
1,Buddy Hield,Atlanta Hawks,G-F,6-4,Oklahoma
2,C.J. McCollum,Atlanta Hawks,G,6-3,Lehigh
3,Caleb Houstan,Atlanta Hawks,F,6-8,Michigan
4,Christian Koloko,Atlanta Hawks,C,7-0,Arizona
...,...,...,...,...,...
521,Sharife Cooper,Washington Wizards,G,6-1,Auburn
522,Trae Young,Washington Wizards,G,6-1,Oklahoma
523,Tre Johnson,Washington Wizards,G,6-5,Texas
524,Tristan Vukcevic,Washington Wizards,C,6-11,NaN


## Convert Data Types with the astype Method II: Categories
- The `category` type is ideal for columns with a limited number of unique values.
- For categories, pandas does not create a separate copy of every string/cell in memory. 
- Rather, Pandas connects each distinct string to a numeric representation. Integers are cheaper to store in memory than strings.

In [94]:
nba_for_cat = pd.read_csv("nba.csv").dropna(how="all")
nba_for_cat.tail()

,Name,Team,Position,Height,Weight,College,Salary
521,Sharife Cooper,Washington Wizards,G,6-1,180.0,Auburn,NaN
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000.0
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000.0
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,NaN,3000000.0
525,Will Riley,Washington Wizards,G-F,6-8,186.0,Illinois,4300000.0


- The `nunique` method returns a count of the number of unique values per column.

In [97]:
nba_for_cat["Team"].nunique()

30

In [98]:
nba_for_cat.nunique()

Name        526
Team         30
Position      5
Height       19
Weight       84
College     137
Salary      199
dtype: int64

- The `Position` and `Team` columns are good candidates to be category columns.
- There are 7 unique positions and 30 unique teams in a DataFrame with ~600 rows.

In [99]:
nba["Position"] = nba["Position"].astype("category")

In [100]:
nba["Team"] = nba["Team"].astype("category")

- Converting to `category` reduces memory usage.

In [101]:
nba.info()

<class 'pandas.DataFrame'>
RangeIndex: 526 entries, 0 to 525
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype   
---  ------    --------------  -----   
 0   Name      526 non-null    str     
 1   Team      526 non-null    category
 2   Position  526 non-null    category
 3   Height    526 non-null    str     
 4   Weight    526 non-null    float64 
 5   College   485 non-null    str     
 6   Salary    526 non-null    Int32   
dtypes: Int32(1), category(2), float64(1), str(3)
memory usage: 33.7 KB


- We've reduced the memory by nearly a third!

## Attribute Namespaces
- Pandas nests related methods underneath attributes/namespaces.

- For example, the `str` attribute holds string methods.

In [102]:
nba["Team"].str.upper()

0           ATLANTA HAWKS
1           ATLANTA HAWKS
2           ATLANTA HAWKS
3           ATLANTA HAWKS
4           ATLANTA HAWKS
              ...        
521    WASHINGTON WIZARDS
522    WASHINGTON WIZARDS
523    WASHINGTON WIZARDS
524    WASHINGTON WIZARDS
525    WASHINGTON WIZARDS
Name: Team, Length: 526, dtype: object

- The `cat` namespace holds methods for categorical columns.
- The `cat.categories` attribute returns the distinct categories for a categorical column.

In [103]:
nba["Position"].cat.categories

Index(['C', 'F', 'F-C', 'G', 'G-F'], dtype='str')

## Sort a DataFrame with the sort_values Method I
- The `sort_values` method sorts a `DataFrame` by the values in one or more columns.
- If sorting by a single column, pass a string with its name.
- The default sort order is ascending (alphabetical for strings).
- The first parameter (`by`) expects the column(s) to sort by.
- The `ascending` parameter customizes the sort order.
- The `na_position` parameter customizes where pandas places `NaN` values.

In [104]:
nba.sort_values(by="Name")

,Name,Team,Position,Height,Weight,College,Salary
280,A.J. Green,Milwaukee Bucks,G,6-4,190.0,Northern Iowa,9400000
474,A.J. Lawson,Toronto Raptors,G,6-6,178.0,South Carolina,0
103,AJ Johnson,Dallas Mavericks,G,6-5,160.0,NaN,3900000
121,Aaron Gordon,Denver Nuggets,F,6-8,235.0,Arizona,31600000
174,Aaron Holiday,Houston Rockets,G,6-0,185.0,UCLA,2300000
...,...,...,...,...,...,...,...
455,Zach LaVine,Sacramento Kings,G-F,6-5,200.0,UCLA,48200000
138,Zeke Nnaji,Denver Nuggets,F-C,6-9,240.0,Arizona,7700000
48,Ziaire Williams,Brooklyn Nets,F,6-8,185.0,Stanford,6000000
332,Zion Williamson,New Orleans Pelicans,F,6-7,284.0,Duke,42200000


## Sort a DataFrame with the sort_values Method II: Multiple Columns
- To sort by multiple columns, pass the `by` parameter a list of column names. Pandas will sort in the specified column order (first to last).
- Pass the `ascending` parameter a Boolean to sort all columns in a consistent order (all ascending or all descending).
- Pass `ascending` a list to customize the sort order *per* column. The `ascending` list length must match the `by` list.

In [106]:
nba.sort_values(by=["Team", "Name"])

,Name,Team,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,F,6-10,220.0,Georgia,4000000
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000
4,Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,0
...,...,...,...,...,...,...,...
521,Sharife Cooper,Washington Wizards,G,6-1,180.0,Auburn,0
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,NaN,3000000


## Sort with Ordered Categories
- By default, category values have no ranking.

- The `nunique` methods returns a count of unique values.
- The `unique` method returns a list of all distinct/unique values.

In [107]:
nba["Team"].unique()

['Atlanta Hawks', 'Boston Celtics', 'Brooklyn Nets', 'Charlotte Hornets', 'Chicago Bulls', ..., 'Sacramento Kings', 'San Antonio Spurs', 'Toronto Raptors', 'Utah Jazz', 'Washington Wizards']
Length: 30
Categories (30, str): ['Atlanta Hawks', 'Boston Celtics', 'Brooklyn Nets', 'Charlotte Hornets', ..., 'San Antonio Spurs', 'Toronto Raptors', 'Utah Jazz', 'Washington Wizards']

- An **ordered** categorical assigns a rank to the sequence (e.g., "Standard" < "Deluxe" < "Suite" < "Presidential").
- We'll create a `CategoricalDtype` instance with an ordered list of categories.
- "Standard" comes before "Deluxe", which comes before "Suite".

In [108]:
# This requires the hotel csv instead...
hotels = pd.read_csv("hotel_bookings.csv")

In [110]:
room_type = pd.CategoricalDtype(
  categories=["Standard", "Deluxe", "Suite", "Presidential"],
  ordered=True
)
hotels["Room"] = hotels["Room"].astype(room_type)

- The `sort_values` method will use category order, not alphabetical order.

In [111]:
hotels.sort_values("Room")

,Hotel,City,Room,Stars,Price,Rating,Nights,Guests,Season
0,Sunset Suites,Las Vegas,Standard,5,185.47,4.3,2,2,Summer
141,Heritage Inn,Las Vegas,Standard,5,163.40,4.5,3,2,Winter
65,Harbor Plaza,New York,Standard,4,126.09,3.8,2,2,Fall
144,Ocean Suites,San Francisco,Standard,5,162.16,4.2,3,3,Fall
63,Mountain Lodge,Denver,Standard,5,177.09,4.4,5,4,Fall
...,...,...,...,...,...,...,...,...,...
183,Royal Resort,Nashville,Presidential,3,688.12,2.6,6,1,Summer
11,Skyline Resort,Las Vegas,Presidential,5,877.54,4.1,4,2,Winter
121,Sunset Suites,Austin,Presidential,4,618.53,3.4,6,1,Fall
128,Harbor Hotel,Las Vegas,Presidential,4,722.12,3.6,2,1,Spring


## Sort a DataFrame by its Index
- The `sort_index` method sorts the `DataFrame` by its index positions/labels.
- Assign back to the original variable to overwrite the old `DataFrame`.

In [112]:
hotels.sort_index()

,Hotel,City,Room,Stars,Price,Rating,Nights,Guests,Season
0,Sunset Suites,Las Vegas,Standard,5,185.47,4.3,2,2,Summer
1,Harbor Hotel,Miami,Suite,4,315.38,3.1,4,3,Fall
2,Sunset Hotel,Nashville,Standard,3,112.52,3.5,7,3,Spring
3,Mountain Suites,Las Vegas,Deluxe,5,285.43,3.9,2,4,Spring
4,Ocean Hotel,New York,Deluxe,3,158.23,2.3,11,2,Spring
...,...,...,...,...,...,...,...,...,...
190,Park Plaza,Denver,Presidential,3,539.51,2.1,3,3,Summer
191,Metro Suites,Denver,Standard,3,91.66,3.3,5,3,Winter
192,Sunset Hotel,Miami,Deluxe,4,210.93,3.1,2,2,Spring
193,Park Resort,Las Vegas,Suite,4,303.90,2.7,2,4,Winter


## Rank Values with the rank Method
- The `rank` method assigns a numeric ranking to each `Series` value.
- Pandas will assign the same rank to equal values and create a "gap" in the dataset for the ranks.

In [115]:
nba["Salary"].rank()

0      241.0
1      346.5
2      464.5
3       98.5
4       26.5
       ...  
521     26.5
522    498.0
523    343.5
524    214.0
525    250.0
Name: Salary, Length: 526, dtype: Float64

In [116]:
nba["Salary Rank"] = nba["Salary"].rank(ascending=False)

In [117]:
nba.sort_values("Salary", ascending=False)

,Name,Team,Position,Height,Weight,College,Salary,Salary Rank
392,Joel Embiid,Philadelphia 76ers,C,7-0,280.0,Kansas,64300000,1.0
22,Jayson Tatum,Boston Celtics,F,6-8,210.0,Duke,62700000,2.0
407,Devin Booker,Phoenix Suns,G,6-5,206.0,Kentucky,62100000,3.0
172,Stephen Curry,Golden State Warriors,G,6-2,185.0,Davidson,61100000,4.0
21,Jaylen Brown,Boston Celtics,G-F,6-6,223.0,California,59000000,5.5
...,...,...,...,...,...,...,...,...
64,Tosan Evbuomwan,Charlotte Hornets,F,6-8,217.0,Princeton,0,500.5
462,Emanuel Miller,San Antonio Spurs,F,6-6,215.0,TCU,0,500.5
74,Lachlan Olbrich,Chicago Bulls,F-C,6-10,235.0,NaN,0,500.5
181,JD Davison,Houston Rockets,G,6-3,175.0,Alabama,0,500.5


- The `method` parameter controls how Pandas assigns a rank when multiple values tie for the same rank.

In [119]:
scores = pd.Series([100, 90, 90, 80])
scores

0    100
1     90
2     90
3     80
dtype: int64

- The `"average"` value (default) uses the average of the rankings.

In [120]:
scores.rank(ascending=False, method="average")

0    1.0
1    2.5
2    2.5
3    4.0
dtype: float64

- The `"min"` value assigns all tied values the lowest rank.

In [121]:
scores.rank(ascending=False, method="min")

0    1.0
1    2.0
2    2.0
3    4.0
dtype: float64

- The `"max"` value assigns all tied values the highest rank.

In [122]:
scores.rank(ascending=False, method="max")

0    1.0
1    3.0
2    3.0
3    4.0
dtype: float64

- The `"dense"` value operates like `"min"` but has gaps in the ranking.
- The values of 90 and 90 tie for a rank of 2.
- The value of 100 is assigned a rank fo 3 instead of 4.

In [123]:
scores.rank(ascending=False, method="dense")

0    1.0
1    2.0
2    2.0
3    3.0
dtype: float64

- The `"first"` value breaks up ties based on the number's position.
- The first occurrence of the duplicate (90) in the `Series` gets the smaller rank.

In [124]:
scores.rank(ascending=False, method="first")

0    1.0
1    2.0
2    3.0
3    4.0
dtype: float64